version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      MONGO_CON_STR: ""

    restart: always
#    command: ["poetry build && /venv/bin/pip install --upgrade pip wheel setuptools && /venv/bin/pip install dist/*.whl","tgcf-web"]